# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [2]:
# Import NumPy as its abbreviation 'np'
import numpy as np


In [4]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1,2,3])
print(a1)

# Create a 2-dimensional NumPy array using np.array()
a2 = np.random.randint(10,size=(2,3))
print(a2)

# Create a 3-dimensional Numpy array using np.array()
a3 = np.random.randint(10,size=(2,3,3))
print(a3)

[1 2 3]
[[3 0 7]
 [0 5 8]]
[[[2 1 2]
  [2 2 0]
  [3 1 2]]

 [[0 9 4]
  [6 7 2]
  [5 0 3]]]


Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [5]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.shape ,a1.ndim, a1.dtype, a1.size, type(a1)

((3,), 1, dtype('int32'), 3, numpy.ndarray)

In [6]:
# Attributes of 2-dimensional array
a2.shape, a2.ndim, a2.dtype, a2.size, type(a2)

((2, 3), 2, dtype('int32'), 6, numpy.ndarray)

In [7]:
# Attributes of 3-dimensional array
a3.shape, a3.ndim, a3.dtype, a3.size, type(a3)

((2, 3, 3), 3, dtype('int32'), 18, numpy.ndarray)

In [11]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd

df = pd.DataFrame(a2)
df

0  1  2
0  3  0  7
1  0  5  8

In [15]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [16]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((7,2,3))
zeros


array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [23]:
# Create an array within a range of 0 and 100 with step 3
a4 = np.arange(0,100,3)
a4


array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [26]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
a5 = np.random.randint(0,10,size=(7,2))
a5

array([[4, 3],
       [5, 7],
       [0, 3],
       [6, 7],
       [0, 7],
       [5, 4],
       [9, 8]])

In [32]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
a6 = np.random.random((3,5))
print(a6)
a6.dtype

[[0.18782398 0.82627519 0.89938864 0.423956   0.59596829]
 [0.46560228 0.91314102 0.22259629 0.99475595 0.70513653]
 [0.64397352 0.61561736 0.88260158 0.05945879 0.34409586]]


dtype('float64')

In [34]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
a7 = np.random.randint(0,10,size=(4,6))
a7

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

ANS = Because, we set value for random as seed.Until we change the number of the seed it won't change it's order

In [37]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
a8 = np.random.randint(0,10,size=(3,7))
print(a8)
# Find the unique numbers in the array you just created
np.unique(a8)

[[3 7 6 8 7 4 1]
 [4 7 9 8 8 0 8]
 [6 8 7 0 7 7 2]]


array([0, 1, 2, 3, 4, 6, 7, 8, 9])

In [38]:
# Find the 0'th index of the latest array you created
a8[0]

array([3, 7, 6, 8, 7, 4, 1])

In [40]:
# Get the first 2 rows of latest array you created
a8[:2]

array([[3, 7, 6, 8, 7, 4, 1],
       [4, 7, 9, 8, 8, 0, 8]])

In [41]:
# Get the first 2 values of the first 2 rows of the latest array
a8[:2,:2]

array([[3, 7],
       [4, 7]])

In [43]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
a8 = np.random.randint(0,10,size=(3,5))
a9 = np.ones((3,5))
print(a8)
print(a9)

[[6 6 7 4 2]
 [7 5 2 0 2]
 [4 2 0 4 9]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [44]:
# Add the two arrays together
a8+a9

array([[ 7.,  7.,  8.,  5.,  3.],
       [ 8.,  6.,  3.,  1.,  3.],
       [ 5.,  3.,  1.,  5., 10.]])

In [45]:
# Create another array of ones of shape (5, 3)
a10 = np.ones((5,3))
a10

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [46]:
# Try add the array of ones and the other most recent array together
a9+a10

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

ANS = Because, both matrices have different size.If we reshape either one of the matrix we can add it.

In [47]:
# Create another array of ones of shape (3, 5)
a11 = np.ones((3,5))
a11

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [55]:
# Subtract the new array of ones from the other most recent array
a8-a11

array([[ 5.,  5.,  6.,  3.,  1.],
       [ 6.,  4.,  1., -1.,  1.],
       [ 3.,  1., -1.,  3.,  8.]])

In [57]:
# Multiply the ones array with the latest array
a12 = a8*a11
a12

array([[6., 6., 7., 4., 2.],
       [7., 5., 2., 0., 2.],
       [4., 2., 0., 4., 9.]])

In [58]:
# Take the latest array to the power of 2 using '**'
a12**2

array([[36., 36., 49., 16.,  4.],
       [49., 25.,  4.,  0.,  4.],
       [16.,  4.,  0., 16., 81.]])

In [62]:
# Do the same thing with np.square()
np.square(a12)

array([[36., 36., 49., 16.,  4.],
       [49., 25.,  4.,  0.,  4.],
       [16.,  4.,  0., 16., 81.]])

In [63]:
# Find the mean of the latest array using np.mean()
a12.mean()

4.0

In [64]:
# Find the maximum of the latest array using np.max()
a12.max()

9.0

In [66]:
# Find the minimum of the latest array using np.min()
a12.min()

0.0

In [67]:
# Find the standard deviation of the latest array
a12.std()

2.581988897471611

In [68]:
# Find the variance of the latest array
a12.var()

6.666666666666667

In [69]:
# Reshape the latest array to (3, 5, 1)
a12.reshape(3,5,1)

array([[[6.],
        [6.],
        [7.],
        [4.],
        [2.]],

       [[7.],
        [5.],
        [2.],
        [0.],
        [2.]],

       [[4.],
        [2.],
        [0.],
        [4.],
        [9.]]])

In [70]:
# Transpose the latest array
a12.T

array([[6., 7., 4.],
       [6., 5., 2.],
       [7., 2., 0.],
       [4., 0., 4.],
       [2., 2., 9.]])

What does the transpose do?

Ans: It flips the order of the array

In [73]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
a13 = np.random.randint(0,10,size=(3,3))
a14 = np.random.randint(0,10,size=(3,2))
print(a13)
print(a14)

[[8 3 8]
 [2 6 5]
 [7 8 4]]
[[0 2]
 [9 7]
 [5 7]]


In [77]:
# Perform a dot product on the two newest arrays you created
a13.dot(a14)

array([[67, 93],
       [79, 81],
       [92, 98]])

In [79]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
a14 = np.random.randint(0,10,size=(4,3))
a15 = np.random.randint(0,10,size=(4,3))
print(a14)
print(a15)


[[4 9 5]
 [6 3 6]
 [7 0 5]
 [7 4 3]]
[[1 5 5]
 [0 8 5]
 [2 3 3]
 [2 9 2]]


In [80]:
# Perform a dot product on the two newest arrays you created
a14.dot(a15)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

Ans: By reshaping one of the matrix or by transporsing it

In [81]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
a14.dot(a15.T)


array([[74, 97, 50, 99],
       [51, 54, 39, 51],
       [32, 25, 29, 24],
       [42, 47, 35, 56]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [82]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
a16 = np.random.randint(0,10,size=(3,4))
a17 = np.random.randint(0,10,size=(3,4))
print(a16)
print(a17)

[[2 3 6 3]
 [8 0 7 6]
 [1 7 0 8]]
[[8 1 6 9]
 [2 6 9 8]
 [3 0 1 0]]


In [83]:
# Compare the two arrays with '>'
a16>a17

array([[False,  True, False, False],
       [ True, False, False, False],
       [False,  True, False,  True]])

What happens when you compare the arrays with `>`?

Ans = It will compare values in both matrices return True if first matrix's value is greater than latter one or return 
false

In [84]:
# Compare the two arrays with '>='
a16>=a17

array([[False,  True,  True, False],
       [ True, False, False, False],
       [False,  True, False,  True]])

In [85]:
# Find which elements of the first array are greater than 7
a16>7

array([[False, False, False, False],
       [ True, False, False, False],
       [False, False, False,  True]])

In [86]:
# Which parts of each array are equal? (try using '==')
a16==a17

array([[False, False,  True, False],
       [False, False, False, False],
       [False, False, False, False]])

In [88]:
# Sort one of the arrays you just created in ascending order
a16.sort()
a16

array([[2, 3, 3, 6],
       [0, 6, 7, 8],
       [0, 1, 7, 8]])

In [89]:
# Sort the indexes of one of the arrays you just created
a16.argsort()

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]], dtype=int64)

In [90]:
# Find the index with the maximum value in one of the arrays you've created
a16.argmax()

7

In [91]:
# Find the index with the minimum value in one of the arrays you've created
a16.argmin()

4

In [47]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created


In [92]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
a16.argmin(axis=0)

array([1, 2, 0, 0], dtype=int64)

In [98]:
# Create an array of normally distributed random numbers
a17 = np.random.random((2,3))
a17

array([[0.89711026, 0.88708642, 0.77987555],
       [0.64203165, 0.08413996, 0.16162871]])

In [107]:
# Create an array with 10 evenly spaced numbers between 1 and 100
a18 = np.linspace(1,100,10)
a18

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.